### ISSUE TITLE
Microsoft.AspNetCore.Razor.Language Version=3.1.1.0

### ISSUE THREAD

**Issue by SemenyakoTaras** [adoconnection/RazorEngineCore#10]
![image](https://user-images.githubusercontent.com/17446422/78027961-eab7e480-7366-11ea-93ec-b5696375a328.png)

Hi there. 
Trying to use your lib in my project with Azure Function.
I am getting the next issue that I mentioned above.

In the output window, it says "Exception thrown: 'System.IO.FileNotFoundException' in RazorEngineCore.dll", but actually my template exists... 

![image](https://user-images.githubusercontent.com/17446422/78028572-e93aec00-7367-11ea-92f6-d0f977900537.png)

I tried to install such Microsoft.AspNetCore.Razor.Language Version=3.1.1 in the project directly, but it still says the same.

Any thoughts?

**Comment by adoconnection** [comment]
If I create new Azure Functions project, this works for me.
You are not supposed to install `Microsoft.AspNetCore.Razor.Language` by your own

```cs

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req, ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            RazorEngine razorEngine = new RazorEngine();
            RazorEngineCompiledTemplate template = razorEngine.Compile("hello @Model.Name");

            template.SaveToFile("template.bin");

            RazorEngineCompiledTemplate template2 = RazorEngineCompiledTemplate.LoadFromFile("template.bin");

            string result = template2.Run(new { Name = name });

            return name != null
                ? (ActionResult)new OkObjectResult(result)
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }
    }
}

```
