### ISSUE TITLE
Cacheing

### ISSUE THREAD

**Issue by timatfourteenfish** [adoconnection/RazorEngineCore#11]
We are currently using RazorEngine like this:
```cs
if (Engine.Razor.IsTemplateCached(TemplateName, typeof(BaseEmailModel)))
{
    parsedContent = Engine.Razor.Run(TemplateName, typeof(BaseEmailModel), model);
}
else
{
    var viewPath = Path.Combine(Statics.EmailTemplatesPath, $"{TemplateName}.cshtml");
    var viewContent = ReadTemplateContent(viewPath);
    parsedContent = Engine.Razor.RunCompile(viewContent, TemplateName, null, model);
}
```
if I use your suggested static cacheing how do I perform a similar test in order to get things moving on?

**Comment by adoconnection** [comment]
Hi! This code do cache template on first run and then run it.
So you can replace it with example https://github.com/adoconnection/RazorEngineCore#caching

Can you please be more specific?

**Comment by adoconnection** [comment]
https://github.com/adoconnection/RazorEngineCore/wiki/Switch-from-RazorEngine-cshtml-templates

**Comment by timatfourteenfish** [comment]
Thanks for that, I had come up with something remarkably similar myself, but then found that I got an error on running as our templates are like this:

@using Fish.EmailModels
@model Fish.EmailModels.Models.PasswordReset

@{
    var link = Model.BaseUrl + "/account/passwordreset/" + Model.Recipient.UserId + "?ec=" + Model.TempResetPassword;
}

<title>Password reset request on @Model.Website.Name</title>

so it says there is an error:
RazorEngineCompilationException: Unable to compile template: 3fip5dfx.jjq(3,7): error CS0246: The type or namespace name 'Fish' could not be found (are you missing a using directive or an assembly reference?)

Is this because the use of the @using Fish.EmailModels is too much? I have tried passing it in using the builder option on the compile but then it says it can't find the dll

**Comment by adoconnection** [comment]
I think you need to remove those lines from template
~~@using Fish.EmailModels~~
~~@model Fish.EmailModels.Models.PasswordReset~~

**Comment by timatfourteenfish** [comment]
But the template needs items in the model so then the system won't compile.How would you pass items in to the template to be displayed?

**Comment by adoconnection** [comment]
With RazorEngineCore it should work just fine. 
Class Library 1
```cs
namespace ClassLibrary1
{
    public class MyModel
    {
        public Recipient Recipient { get; set; }
    }

    public class Recipient
    {
        public string Name { get; set; }
    }
}
```

Main project:
```cs
class Program
{
    static void Main(string[] args)
    {
        RazorEngine engine = new RazorEngine();
        RazorEngineCompiledTemplate razorEngineCompiledTemplate = engine.Compile("Hello, @Model.Recipient.Name");

        MyModel model = new MyModel()
        {
            Recipient = new Recipient()
            {
                Name = "timatfourteenfish"
            }
        };

        Console.WriteLine(razorEngineCompiledTemplate.Run(model));

        Console.ReadKey();
    }
}
```

**Comment by timatfourteenfish** [comment]
ok, but doesn't that negate the benefit of having a pre-written Razor template that you want to populate with model data before generating html for emailing out?

**Comment by adoconnection** [comment]
You mean pre-compiled? Not sure I get you correctly.
