### ISSUE TITLE
Include and Layout Wiki is outdated with current RazorEngine.Compile() method

### ISSUE THREAD

**Issue by bastienJS** [adoconnection/RazorEngineCore#110]
check this link: https://github.com/adoconnection/RazorEngineCore/wiki/@Include-and-@Layout

With the latest RazorEngineCore version the .Compile("template") has no overload to accept a Dictionary<string, string> like you show in your wiki documentation. 

How do I pass the parts to the Compile method then? Can not find any sample! :-)

**Comment by bastienJS** [comment]
OK I could not believe that there is unversioned code below in the wiki which I should copy/paste into my solution because of the comment: Maintainer strongly believes implementing @include and @Layout is unnecessary complexity for standalone RazorEngine.

very unusual approach!

**Comment by adoconnection** [comment]
Hi, it helps to keep breaking changes as low as zero :)
