### ISSUE TITLE
System.TypeLoadException.

### ISSUE THREAD

**Issue by Federico-Luna** [adoconnection/RazorEngineCore#112]
Following the basic usage, I'm trying to compile a razor page to generate the html for an order and send it via email, but I get this error when I try to compile it:

Message=Method 'CreateDeterministicKeyBuilder' in type 'Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions' from assembly 'Microsoft.CodeAnalysis.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
  Source=RazorEngineCore

The api:
`        

        [HttpGet("GenerahtmlPedido/{idPedido}")]
        public ActionResult<string> GenerahtmlPedido(int idPedido)
        {
            DirectoryInfo dinfo = new DirectoryInfo(Path.Combine(_environment.ContentRootPath, "pages"));
            var cshtmlFile = Path.Combine(dinfo.FullName, "Pedido.cshtml");

            string strPageContent, strHtml;

            using (StreamReader r = new StreamReader(cshtmlFile))
            {
                strPageContent = r.ReadToEnd();

                IRazorEngine razorEngine = new RazorEngine();
                IRazorEngineCompiledTemplate template = razorEngine.Compile(strPageContent);

                strHtml = template.Run(new { id = idPedido });
            }

            return strHtml;
        }

`
Thank you very much.

Attached razor page to compile and models.
[RazorPage&Models.zip](https://github.com/adoconnection/RazorEngineCore/files/9086494/RazorPage.Models.zip)

**Comment by adoconnection** [comment]
Hi, your page "Pedido" has a lot of extra stuff in it. like @htmllocalizer
Start with something simple. Pass PedidoModel and try render something like <p>@Model.Pedido.Id</p> 
then add other things so you will instantly see what caused a problem 👍

**Comment by Federico-Luna** [comment]
@htmlLocalizer is for localization, spain spanish, Peru spanish, USA English, British English, etc. and is mandatory, but I'll try to put literals instead of @htmllocalizer and try step by step.

Thank you again.

**Comment by Federico-Luna** [comment]
The new Pedido. I get same error.
[NewSimplePedido.zip](https://github.com/adoconnection/RazorEngineCore/files/9087503/NewSimplePedido.zip)

**Comment by Federico-Luna** [comment]
Ok. Thank you very much for your help.
