### ISSUE TITLE
Dotnet 7/C#11 Support

### ISSUE THREAD

**Issue by hughesjs** [adoconnection/RazorEngineCore#121]
We're about to migrate our solutions over from [Antaris' dead RazorEngine](https://github.com/Antaris/RazorEngine). This is primarily because I've just ran into an issue where it can't handle `init` properties on models... I guess its code generator is too old.

I just wanted to check whether you're planning to support dotnet 7 once it's released next month and how much work it would be for you to get that working? We're particularly wanting to make sure we'll be able to use `required` props once they're released.

**Comment by adoconnection** [comment]
I expect RazorEngineCore to work in net7 out of the box.
In a past it only broke once when net5 was released, and the problem was very specific with single file deployments (see #38)

You are good to go with net7 and RazorEngineCore

**Comment by hughesjs** [comment]
Nice one, that's great to know, I've just got to the migration this sprint, so will let you know if I run into any issues :)
