### ISSUE TITLE
Support for init-only setters

### ISSUE THREAD

**Issue by hughesjs** [adoconnection/RazorEngineCore#123]
Legacy `RazorEngine.NetCore` doesn't work if you've got `init` setters on your models. I strongly suspect it's just because it's using a very, very old code generator that doesn't understand them, but I've not verified that.

Is that supported in this project?

**Comment by adoconnection** [comment]
does this helps?
https://github.com/adoconnection/RazorEngineCore#strongly-typed-model

Making new model instance is on your side so I see no issues with init only properties
