### ISSUE TITLE
Documentation update to improve usage experience: @Inherits directive

### ISSUE THREAD

**Issue by AndyMDoyle** [adoconnection/RazorEngineCore#13]
Firstly thank you for this project. I have battled with various other packages and couldn't get them to work reliably with .NET Core 3.1 running in an Azure Function. Yours works perfectly.

Here's something I feel would improve the user experience if it was documented...

For anyone who is storing their templates in CSHTML files either in the file system or as an embedded resource, the lack of the @model and @using statements mean you can't benefit from Visual Studio's IntelliSense when editing the files. You end up with lots of warnings in the code whereever you reference @Model.Property, or @Include (if you are implementing the @include support from your wiki).

I have found that when using a strongly typed model, adding an @inherits directive to the file greatly improves this.

`@inherits RazorEngineCore.RazorEngineTemplateBase<MyModel>`

Or in my case where I'm using a custom template base to implement the include functionality, I'm using:

`@inherits FunctionsApp1.Email.CustomRazorEngineTemplateBase<MyClassLib.EmailModels.WelcomeModel>`

I hope this helps.

**Comment by adoconnection** [comment]
Thank you for the kind words. Im surprised RazorEngine dont mind to see several `@include` directives :)

https://github.com/adoconnection/RazorEngineCore/wiki/Switch-from-RazorEngine-cshtml-templates

**Comment by Sushi21** [comment]
@AndyMDoyle 

Im trying to run few tests before deciding to use or not that library for our future pdf engine

I'm having some compile error when Im adding that line at the top of my template

![image](https://user-images.githubusercontent.com/35455125/114096403-0b2d4f80-9895-11eb-8c0a-c13b6e3de834.png)
Do I miss any nuget other that RazorEngineCore?

I'm using Core3.1 API

**Comment by jackhamby** [comment]
can we get this opened up again. the linked issue is completely separate. im having the same issue running in net5.0
<img width="685" alt="error" src="https://user-images.githubusercontent.com/38231373/125891954-fff67a31-5b58-4a6e-bf5d-dbcf68e8f91f.png">

**Comment by adoconnection** [comment]
I have attached sample ConsoleApp48 that runs on NET5
* dont forget to put full namespace in inherits: ```@inherits RazorEngineCore.RazorEngineTemplateBase<ConsoleApp48.EmailModel>```
* Autocomplete works in VS2019 but not in VS2022 preview

[ConsoleApp48.zip](https://github.com/adoconnection/RazorEngineCore/files/6829651/ConsoleApp48.zip)


```cs
using RazorEngineCore;
using System;
using System.IO;

namespace ConsoleApp48
{
    class Program
    {
        static void Main(string[] args)
        {
            RazorEngine razorEngine = new RazorEngine();
            string templateText = File.ReadAllText("Template.cshtml");

            IRazorEngineCompiledTemplate<RazorEngineTemplateBase<EmailModel>> compiledTemplate = razorEngine.Compile<RazorEngineTemplateBase<EmailModel>>(templateText);

            string result = compiledTemplate.Run(instance => {
                instance.Model = new EmailModel
                {
                    Email = "mail@example.com",
                    FirstName = "Jack"
                };
            });

            Console.WriteLine(result);

            Console.ReadKey();
        }
    }
}
```

```cs
namespace ConsoleApp48
{
    public class EmailModel
    {
        public string Email { get; set; }
        public string FirstName { get; set; }
    }
}
```

```html
@inherits RazorEngineCore.RazorEngineTemplateBase<ConsoleApp48.EmailModel>

<html>
    <body>
        <h1>Hello @Model.FirstName</h1>
    </body>
</html>
```

**Comment by jackhamby** [comment]
thanks for taking a look. i ran your stuff locally and it does work perfectly.

the code you have for the template and compiling is nearly exactly the same as what we have.

main difference i see is this is a **console app** whereas we have **ASP.NET core MVC app.** 

i spun up an mvc app that tries to compile a single template with the @inherits directive and return an OK result with the resulting string. it blows up in the same way as our actual application (which is during the build with the same errors i posted above)

if you clone this repo and try to build it, you should see the same
https://github.com/jackhamby/RazorEngineCoreError

again thanks for looking, any advice is greatly appreciated

**Comment by wdcossey** [comment]
The most likely scenario is that the `.cshtml` is being compiled automatically during the build process (i.e via `Sdk.Razor.CurrentVersion.props`.
Basically you are building an MVC app so it will try compile all the `.cshtml` files it finds.

**Comment by jackhamby** [comment]
thanks @wdcossey.
changing the extension does work, i did .cshtml -> .mcshtml and i was able to compile successfully.
do you know how to handle this in the .csproj instead? it would be nice to keep .cshtml extention so at least VS recognizes the extension.

**Comment by wdcossey** [comment]
@jackhamby something like the following.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <EnableDefaultContentItems>false</EnableDefaultContentItems>
    </PropertyGroup>

    <ItemGroup Condition="'$(EnableDefaultItems)' == 'true' And '$(EnableDefaultContentItems)' == 'false'">
        <Content Include="**\*.cshtml" 
                 ExcludeFromSingleFile="true" 
                 CopyToPublishDirectory="PreserveNewest" 
                 Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder);$(DefaultWebContentItemExcludes);Templates\**\*.cshtml" />
        <None Remove="**\*.cshtml" />
        <Content Include="Templates\Template.cshtml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
```

**Comment by wdcossey** [comment]
`EnableDefaultContentItems` is from `Sdk.Razor.CurrentVersion.props`, I just changed the logic slightly.

```
    <!--
    Set to true to automatically include certain file types, such as .cshtml files, as content in the project.
    When referenced via Microsoft.NET.Sdk.Web, this additionally includes all files under wwwroot, and any config files.
    -->
    <EnableDefaultContentItems Condition="'$(EnableDefaultContentItems)'==''">true</EnableDefaultContentItems>
```

Default code:

```
  <ItemGroup Condition="'$(EnableDefaultItems)' == 'true' And '$(EnableDefaultContentItems)' == 'true'">
    <Content Include="**\*.cshtml" ExcludeFromSingleFile="true" CopyToPublishDirectory="PreserveNewest" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder);$(DefaultWebContentItemExcludes)" />
    <Content Include="**\*.razor" ExcludeFromSingleFile="true" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder);$(DefaultWebContentItemExcludes)" />
    <None Remove="**\*.cshtml" />
    <None Remove="**\*.razor" />
  </ItemGroup>
```

**Comment by jackhamby** [comment]
thanks for all this. i played around with those snippets you sent but kept having the same issue. this weekend i finally got something to work. i changed the BuildAction property on the .cshtml file itself, from Content to EmbeddedResource. 

![image](https://user-images.githubusercontent.com/38231373/126201273-01112da0-d9f4-44a4-90c9-0c0dc7cc74d2.png)

once i got that switched over i could build and run. compilation works great as well as the intellisense provided by @inherits directive. thanks again for the help in this.

**Comment by vukasinpetrovic** [comment]
@jackhamby Man, you saved me. That's what I needed. Thank you very much!
