### ISSUE TITLE
HtmlSafeTemplate broken after upgrading from 2022.8.1 to 2023.11.2

### ISSUE THREAD

**Issue by rekna1** [adoconnection/RazorEngineCore#136]
HtmlSafeTemplate overrides some methods like 
public override Task WriteAsync(object obj = null)
public override Task WriteAttributeValueAsync(string prefix, int prefixOffset, object value, int valueOffset, int valueLength, bool isLiteral)

but these methods do not seem to be implemented anymore by RazorEngineTemplateBase.

Is it safe to simply replace it with the non-async equivalents?
Consider updating the example.

Update: seems to work...

**Comment by adoconnection** [comment]
Hi, yes, async methods make no sense there so I decided to remove them.

https://github.com/adoconnection/RazorEngineCore/wiki/@Raw
