### ISSUE TITLE
Extending RazorEngineCore

### ISSUE THREAD

**Issue by wdcossey** [adoconnection/RazorEngineCore#17]
@adoconnection 

Can you have a look at this commit on my (working) fork of **RazorEngineCore**

https://github.com/wdcossey/RazorEngineCore/commit/4751912c633994a328f0661b026812b33578b5d9

This will have some breaking changes for [Strongly typed model](https://github.com/adoconnection/RazorEngineCore/wiki/Strongly-typed-model)
The only actual breaking change is you will always have to use `@Model.` when using `RazorEngineTemplateBase<T>`

for example 
```
string content = @"Hello @A, @B, @Decorator(123)";
```
will have to be rewritten as:
```
string content = @"Hello @Model.A, @Model.B, @Model.Decorator(123)";
```
which will behave like `real` Razor `PageModel`.

These changes will greatly improve the ability to extend **RazorEngineCore** with the use of the Interfaces (that are also in the branch).

My company is shifting to .Net Core from RazorEngine (for .Net Framework) and I need to extend RazorEngineCore rather than creating another private fork.

If you have time, pull that branch have a look at the code and templates.

**Comment by adoconnection** [comment]
Can you tell what are you trying to achive so I can understand your context a little?

Making ```Compile<TModel>(...)``` and ```Run<TModel>(obj)``` was my first though, then I decided to go deeper and introduce ```Run<TTemplate>(instance => {... })``` – with small overhead I was finally able to quickly add template "native" functions and callbacks like ```... @resources.getImage() ... ```

From user's perspective all you do is changing
```cs
RazorEngineCompiledTemplate<RazorEngineTemplateBase<TestModel>> template = razorEngine.Compile<RazorEngineTemplateBase<TestModel>>(content);

string result = template.Run(instance =>
{
    instance.Model = new TestModel()
    {
        Name = "Hello",
        Items = new[] {3, 1, 2}
    };
});
```

to this
```cs
RazorEngineCompiledTemplate<TestModel> template = razorEngine.Compile<TestModel>(content);

string result = template.Run(new TestModel()
    {
        Name = "Hello",
        Items = new[] {3, 1, 2}
    });
```
but why?

**Comment by adoconnection** [comment]
May it be a good moment for extension methods?

```cs
public static MyCompiledTemplate<TModel> CompileForModel<TModel>(this RazorEngine razorEngine, string template)
{
          // RazorEngineCompiledTemplate<RazorEngineTemplateBase<T>>
          var template = razorEngine.Compile<RazorEngineTemplateBase<T>>(template);

          return MyCompiledTemplate<T>(template); // your wrapper with Run<TModel>(obj)
}
```

**Comment by wdcossey** [comment]
@adoconnection 

My idea was to make the model behave more like the Razor PageModel in AspNetCore, using `@Model.Property` rather than `@Property` directly, we have loads of templates that need to be updated from the older `RazorEngine`.

I'd be happier extending `RazorEngineCore` and publishing my changes pack via a separate NuGet package that extends on your work than making yet another RazorEngine package. 🤣 

To be honest I don't really need the `RazorEngineTemplateBase<T>` class implementation but rather the Interfaces (`IRazorEngineTemplateBase` and `IRazorEngineTemplateBase<T>`) so I can extend RazorEngineCore to use custom classes (implementing the Interfaces).

I will make some tweaks and get it back to what is was with just the interfaces and see how that works.

This is what I was thinking for my custom template 
```
public class AwesomeTemplate : RazorEngineTemplateBase, IRazorEngineTemplateBase
{
        // Adds back (some) @Html ability to the template
        // i.e. 
        // @Html.Encode()
        // @Html.AttributeEncode()
        // @Html.Raw() as AwesomeTemplate will be "HTML safe" by default
        public CustomHtmlWriter Html => new CustomHtmlWriter ();

        public void DoSomething(string something = null)
        {
            // do something here
        }

        public override void Write(object value)
        {
            // do some custom logic here
            // write to StringBuilder, TextWriter, etc.
        }

        public override string Result()
        {
            // finish up and output to StringBuilder, TextWriter, etc.
        }
}
```
Maybe make some additional methods in `RazorEngineTemplateBase` as virtual/protected, i.e. `public virtual string Result()`, `public virtual void Write(object value)`, etc.

**Comment by adoconnection** [comment]
Got it, first of all, all methods of RazorEngineTemplateBase should become virtual and probably interface IRazorEngineTemplateBase should be extracted.
This will instantly free your hands in reproducing old RazorEngine behavior.
I used abstract class insted of interface due to my lazyness, there was no special idea behind that.

If you like to use ```@Model.Property``` this code does exactly what you need, are you looking for something else? :)
```
string content = "Hello @Model.Property <a href=\"@Html.Action(....)\">123</a>";
```

```cs
RazorEngineCompiledTemplate<RazorEngineTemplateBase<MyModel>> template = razorEngine.Compile<RazorEngineTemplateBase<MyModel>>(content);

string result = template.Run(instance =>
{
    instance.Html = CustomHtmlWriter();
    instance.Model = new MyModel()
    {
        Property = "123"
    };
});
```

**Comment by adoconnection** [comment]
Nuget version 2020.5.2 ready
https://www.nuget.org/packages/RazorEngineCore

* IRazorEngineTemplate interface
* RazorEngineTemplateBase methods go virtual

**Comment by wdcossey** [comment]
Been tracking your changes as I was making my own, looks like we were doing the same thing (my interface names were different). 😆 

Merged your changes with mine and did some post merge clean-up.

https://github.com/adoconnection/RazorEngineCore/pull/19/commits

**Comment by wdcossey** [comment]
Created a new Template and bunch of extensions for RazorEngineCore, you can find it here
https://github.com/wdcossey/RazorEngineCore.Extensions
