### ISSUE TITLE
Raw

### ISSUE THREAD

**Issue by roja** [adoconnection/RazorEngineCore#2]
Is there a way of causing RazorEngineCore to output a raw string within a template? Full fat razor does so using @Html.Raw(<string>).

**Comment by adoconnection** [comment]
Hi, its default behaviour here, and you should manually encode values to prevent XSS

```
RazorEngine razorEngine = new RazorEngine();
RazorEngineCompiledTemplate template = razorEngine.Compile("Hello @Model.Name");

string result = template.Run(new
{
    Name = "<b>Test</b>"
});

Console.WriteLine(result);
```
will output
```
Hello <b>Test</b>
```

**Comment by roja** [comment]
Thanks for clarifying. Seems like a good default!
