### ISSUE TITLE
Calling extension methods from template

### ISSUE THREAD

**Issue by AndyMDoyle** [adoconnection/RazorEngineCore#22]
Hi,

Is there a way to call extension methods from templates?

I have an object in an external assembly, and in that assembly there is a public static class without a namespace that contains some extension methods for that object.

I want to call `@Model.MyObject.MyExtensionMethod(parameter)` from within the template, but I get a `Microsoft.CSharp.RuntimeBinder.RuntimeBinderException` exception throw with the error:

 `'MyLibrary.MyObject' does not contain a definition for 'MyExtensionMethod'`

I have tried adding a reference to MyLibrary this way:

```
var template = razorEngine.Compile<RazorEngineTemplateBase<TestModel>>(content, builder =>
{
	builder.AddAssemblyReference(typeof(MyLibrary.MyObject));
});
```

But without any luck.

Is this achievable?

**Comment by adoconnection** [comment]
Sure, you need to reference extension method assembly, not a model.
Also you need to add ```@using``` directive, either in template body or in ```builder.AddUsing("Assembly2");``` (will do the same)

Have a look at my test app:

![image](https://user-images.githubusercontent.com/499855/86298667-ebcb0d00-bc06-11ea-82a5-3106b1d21c0c.png)

**Comment by AndyMDoyle** [comment]
Perfect, thank you.

We had a custom razor engine setup that was utilizing the non-generic overrides to generate the template and this appears to be the cause. As the model is wrapped as an anonymous type it appears to affect the template generation, particularly in that with the anonymous model we found we had to specifically cast the properties of the model like this:

```c#
@(((MyLibrary.MyObject)Model.Value).MyExtensionMethod())
```

However I have added generic support to our custom engine so we can pass a strongly typed model and cut out this casting in the markup.

Thanks again.

**Comment by adoconnection** [comment]
You welcome.

For my CMS I prefer to add helpers in TemplateBase, imo it makes cshtml code looks clean and nice.

```pageData```, ```FileUrl``` and ```Prettify``` are TemplateBase members and I dont use ```Model``` keyword at all since it does not add any value.

```html
<div>
    @foreach(var document in pageData.documents)
    {
           if (document .file == null)
           {
                  continue;
           }

           <a href="@FileUrl(document .file)">document.title</a>
           <div>@Prettify(document.summary)</div>
    } 
</div>
```
