### ISSUE TITLE
HTML encoding by default

### ISSUE THREAD

**Issue by Tyrrrz** [adoconnection/RazorEngineCore#26]
I was checking out this project and saw on [this page](https://github.com/adoconnection/RazorEngineCore/wiki/@Raw) that the output of `@Foo` is not HTML-encoded by default. Why was this design decision made?

I'd like to use RazorEngineCore for rendering HTML reports, so I would really prefer it encoded content by default and let me use `@Raw` in rare cases where I don't need it.

**Comment by adoconnection** [comment]
Hi, its default AspNetCore.Razor behavior.
Mvc as we know it add its own html safly logic: wrap every value with HtmlValue class with IsRaw property or something like this.

I think you wont need @Raw much for reports (why?) so you can use code from extension method from that page or override template base class, whatever is preferrable for you

```cs
public class RazorEngineTemplateSafe : RazorEngineTemplateBase
{
    public override void Write(object obj = null)
    {
        base.Write(HttpUtility.HtmlEncode(obj));
    }

    public override void WriteAttributeValue(string prefix, int prefixOffset, object value, int valueOffset, int valueLength, bool isLiteral)
    {
        base.WriteAttributeValue(prefix, prefixOffset, HttpUtility.HtmlAttributeEncode(value?.ToString()) , valueOffset, valueLength, isLiteral);
    }
}
```

```cs
var template = razorEngine.Compile<RazorEngineTemplateSafe>(Content);
```

**Comment by Tyrrrz** [comment]
Thanks!

**Comment by wdcossey** [comment]
You can use this extension that adds back the default encoding.

https://github.com/wdcossey/RazorEngineCore.Extensions/tree/master
