### ISSUE TITLE
assembly.GetType returning null, and "Could not load file or assembly RazorEngineCore"

### ISSUE THREAD

**Issue by Merlin04** [adoconnection/RazorEngineCore#27]
I'm working on a PR that will add support for compiling multiple templates in one assembly, but I can't get any of the unit tests that involve running a template to run successfully. I get an exception like this:

```c#
Test method RazorEngineCore.Tests.TestCompileAndRun.TestCompileAndRun_HtmlLiteral threw exception: 
System.ArgumentNullException: Value cannot be null. (Parameter 'type')
    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at RazorEngineCore.RazorEngineCompiledTemplate.RunAsync(Object model)
```

It seems like the issue is with line 18 of RazorEngineCompiledTemplate.cs:

```c#
this.templateType = assembly.GetType("TemplateNamespace.Template");
```

The call to `GetType` doesn't throw an exception, but it returns null. If I use the debugger to look at the `DefinedTypes` property of `assembly`, I get this exception:

```c#
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'RazorEngineCore, Version=2020.6.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

Any idea why I'm getting this error?

**Comment by adoconnection** [comment]
Can you push your code to github so I can examine it?
https://github.com/Merlin04/RazorEngineCore

**Comment by Merlin04** [comment]
This is happening even when I make a new clone of the repository, so it isn't related to my changes.

**Comment by adoconnection** [comment]
It’s hard to tell without seeing a code :)

**Comment by wdcossey** [comment]
If you want to precompile templates during the build process (not runtime) and embed then as resources have a look at my repository.

https://www.nuget.org/packages/RazorEngineCore.Precompiler/

https://github.com/wdcossey/RazorEngineCore.Extensions

There's a project called RazorEngineCore.Precompiler that will do this, you can use it as a starting point.

**Comment by Merlin04** [comment]
The code I'm trying to run the tests for is this repository, not my modifications.

I run:
```
git clone https://github.com/adoconnection/RazorEngineCore
```
Then open the solution in Rider, and try running the tests, but it fails.

**Comment by Merlin04** [comment]
The tests run successfully with `dotnet test`, so this must be an issue with Rider.

**Comment by Merlin04** [comment]
Just found an update that fixes the Rider issue (EAP9)
