### ISSUE TITLE
Nullables treated as non-nullable at runtime

### ISSUE THREAD

**Issue by farlee2121** [adoconnection/RazorEngineCore#33]
My model includes a `DateTime?` property

```cs
public class CampaignDesignerRequest
{
     //...
     public DateTime? CampaignStartDate { get; set; }
     //...
}
```

My view inherits the model 
```cs
@inherits RazorEngineCore.RazorEngineTemplateBase<Fourstarzz.Accessors.ReportTemplates.Models.DesignedCampaign_RenderModel>
```

At write time, the intellisense recognizes CampaignStartDate as a nullable and shows an error hint if I try to run date string formatting without specifying `.Value`
```cs
Model.CampaignStartDate.Value.ToShortDateString()
```

However when I run the code, it gives me the error

>Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : 'System.DateTime' does not contain a definition for 'Value'

I've tested the same on other value types, like int and double, and get the same kind of error.

Versions
- RazoreEngineCore 2020.9.1
-  .NET framework 4.8.

Any thoughts on potential causes?

**Comment by farlee2121** [comment]
I think I may have a lead. Trying to use Linq select was causing a 

> Cannot use a lambda expression as an argument to a dynamically dispatched operation without first casting it to a delegate or expression tree type

This can be [caused by using Linq on dynamic models](https://stackoverflow.com/questions/27169521/cannot-use-a-lambda-expression-as-an-argument-to-a-dynamically-dispatched-operat). The non-generic template base uses dynamic as the type for the whole page model. https://github.com/adoconnection/RazorEngineCore/blob/master/RazorEngineCore/IRazorEngineTemplate.cs

I'm guessing there is some issue with dynamic typing going on here

**Comment by adoconnection** [comment]
As I can see your view inherits different model ```DesignedCampaign_RenderModel``` whereas you looking at ```CampaignDesignerRequest```

**Comment by adoconnection** [comment]
Also, I get same error as this if I do caching, see #28

**Comment by farlee2121** [comment]
Woops, I copied the wrong model statement. CampaignDesignerRequest is actually a property on the other model, but I had been running experiments on a simplified version to make sure the parent object wasn't part of the issue.

I am caching as in issue #28. I'll have to test if the issue also happens with model-specific template caches.

**Comment by farlee2121** [comment]
Ok. I ran a few tests. Using definitely typed templates as you did above, with model-specific caches, and [by casting the cache](https://github.com/adoconnection/RazorEngineCore/issues/28#issuecomment-669796481) solves the issue.

It also works to cast types within the template, though that could be a bit dangerous.

Definitely a good gotcha to have documented

**Comment by farlee2121** [comment]
I'd be happy to contribute documentation if we want to promote it from an issue to the wiki or readme

**Comment by adoconnection** [comment]
you are welcome to push updates in description and wiki :)

**Comment by farlee2121** [comment]
I'll try to push some changes this week
