### ISSUE TITLE
Linq functions I can use in template

### ISSUE THREAD

**Issue by linkopingsommen** [adoconnection/RazorEngineCore#35]
What im doing wrong here:

```
@using System.Linq
@inherits RazorEngineCore.RazorEngineTemplateBase<SummaryData>

<div>
@if (Model.Data.Any()) {
}
</div>
```

we did add references

```
var compiletView = await razorEngine.CompileAsync(view, builder =>
                    {
                        builder.AddAssemblyReferenceByName("System.Linq");
                        builder.AddAssemblyReference(typeof(System.Linq.Enumerable));
                    });
```

but we get error that Any is not a function
`System.Private.CoreLib: Exception while executing function: PDFGenerator. Anonymously Hosted DynamicMethods Assembly: 'object' does not contain a definition for 'Any'`

Data is property used from model is `IEnumerable<stirng>`

'Any' or FirstOrDefault or any Linq method are not working

**Comment by adoconnection** [comment]
Looks like you are using stornly typed model, but compiling and running template with dynamic model.
this should work fine:

```cs
var compiletView = await razorEngine.CompileAsync<RazorEngineTemplateBase<TestModel>>(view, builder => ...
```

```cs
var result = await template.RunAsync(instance =>
{
    instance.Model = new SummaryData()
    {
        ....
    };
});
```

**Comment by adoconnection** [comment]
However its nice to have ```Sytem.Collections``` and ```System.Collections.Generic``` referenced by default, this will go into next release

**Comment by adoconnection** [comment]
for anyone stuck with this, see unit test
https://github.com/adoconnection/RazorEngineCore/blob/6ce357b4be351a3cdff8a6b77bc99c4c5445abbe/RazorEngineCore.Tests/TestCompileAndRun.cs#L449
