### ISSUE TITLE
RazorEngineCore.RazorEngine.Compile not work when publish to single file

### ISSUE THREAD

**Issue by jddj007-hydra** [adoconnection/RazorEngineCore#38]
target framework is .net5  
when i publish exe to single file  ,compile a templeate ,get this error:
System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at RazorEngineCore.RazorEngine.<>c.<CreateAndCompileToStream>b__4_1(Assembly ass)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at System.Linq.Enumerable.ConcatIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RazorEngineCore.RazorEngine.CreateAndCompileToStream(String templateSource, RazorEngineCompilationOptions options)
   at RazorEngineCore.RazorEngine.Compile(String content, Action`1 builderAction)

if not single file , it ok

**Comment by jddj007-hydra** [comment]
i try to debug find this :
ass name System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e  C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\System.Private.CoreLib.dll
ass name Microsoft.CSharp, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a  C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\Microsoft.CSharp.dll
ass name RazorEngineCore, Version=2020.10.1.0, Culture=neutral, PublicKeyToken=null
when MetadataReference.CreateFromFile(ass.Location)   ass is razorEngineCore   it's  Location is null

**Comment by jddj007-hydra** [comment]
looks like  “MetadataReference.CreateFromFile” method not support  Single-File Apps

**Comment by jddj007-hydra** [comment]
[https://github.com/dotnet/runtime/issues/36590#issuecomment-689883856](url) referance this 
modify CreateAndCompileToStream  
...`
  CSharpCompilation compilation = CSharpCompilation.Create(
                fileName,
                new[]
                {
                    syntaxTree
                },
                options.ReferencedAssemblies
                    .Select(ass =>
                    { 
                        unsafe
                        {
                            ass.TryGetRawMetadata(out byte* blob, out int length);
                            var moduleMetadata = ModuleMetadata.CreateFromMetadata((IntPtr)blob, length);
                            var assemblyMetadata = AssemblyMetadata.Create(moduleMetadata);
                            var metadataReference = assemblyMetadata.GetReference();
                            return metadataReference;
                        } 
                        // return  MetadataReference.CreateFromFile(ass.Location); 
                    })
                    .Concat(options.MetadataReferences)
                    .ToList(),
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
....
`
it's worked

**Comment by adoconnection** [comment]
Interesting! thanks for pointing out!

**Comment by kobruleht** [comment]
I got this error also in Linux. 
Will this change added to nuGet package ?

**Comment by afucher** [comment]
Still having this issue with the latest version.

@jddj007-hydra how did you make it works?

**Comment by adoconnection** [comment]
It’s not yet in release

**Comment by afucher** [comment]
@adoconnection any Idea when it will be?

**Comment by adoconnection** [comment]
@kobruleht @afucher @jddj007-hydra 
Can anyone help me reproduce this problem.
I created console app with code from MetadataReference unit test, published it as self contained single file and it worked.

See ``` TestCompileAndRun_MetadataReference```
https://github.com/adoconnection/RazorEngineCore/blob/7edfa1eff96dfe522d2dde074173e9ca1bb5727b/RazorEngineCore.Tests/TestCompileAndRun.cs#L503

**Comment by kobruleht** [comment]
Can you try it in .NET 5 by changing TargetFramework attribute in project file:

```
  <PropertyGroup>
    <!-- <TargetFramework>netcoreapp3.1</TargetFramework>-->
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

```

**Comment by adoconnection** [comment]
got the exception. apparently its a NET5 breaking change...

**Comment by afucher** [comment]
Hey @adoconnection do you have any update on this? Can I help you in any way?

**Comment by adoconnection** [comment]
@jddj007-hydra @afucher @kobruleht 
package 2021.3.1 published!
https://www.nuget.org/packages/RazorEngineCore/2021.3.1

**Comment by afucher** [comment]
I made a quick test here, and it gives me error:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM6T394B63R1", Request id "0HM6T394B63R1:00000007": An unhandled exception was thrown by the application.
      System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
         at System.IO.Path.Combine(String path1, String path2)
         at PugPdf.Core.WkHtmlToPdfDriver.GetExecutablePath()
         at PugPdf.Core.WkHtmlToPdfDriver.GetPath()
         at PugPdf.Core.WkHtmlToPdfDriver.ConvertAsync(String html, String switches)
         at PugPdf.Core.HtmlToPdf.RenderHtmlAsPdfAsync(String html)
```

**Comment by adoconnection** [comment]
Is it RazorEngineCore exception? Any steps to reproduce would be helpful

**Comment by afucher** [comment]
Sorry, it is not. Is another library... my mistake 😞

**Comment by adoconnection** [comment]
Closing issue then :)
