### ISSUE TITLE
Issue with including variables within cshtml attributes

### ISSUE THREAD

**Issue by roja** [adoconnection/RazorEngineCore#4]
RazorEngine razorEngine = new RazorEngine();
            RazorEngineCompiledTemplate template = razorEngine.Compile("<div class=\"circle\" style=\"background-color: hsla(@Model.Colour, 70%, 80%, 1);\">");

            string actual = template.Run(new
            {
                Colour = 88
            });

actual is incorrectly generated as:

    <div class="circle" style="background-color:" style="hsla(" style="88" style="," style="70" style="%," style="80" style="%," style="1);">

**Comment by adoconnection** [comment]
Thanks for unit test, fixed
`Install-Package RazorEngineCore -Version 2020.3.1`

**Comment by roja** [comment]
Fantastic. Thanks for the quick fix.
