### ISSUE TITLE
Update referenced NuGet packages to newer versions

### ISSUE THREAD

**Issue by TheDanielDoyle** [adoconnection/RazorEngineCore#43]
Hi, would it be possible to update the NuGet packages RazorEngineCore uses? The ones currently in the latest release are quite out of date.

For instance, Microsoft.AspNetCore.Razor.Language is at 5.0.2 at this time.

**Comment by adoconnection** [comment]
Hi, It's because net core version jumped from 3.1 to 5.0
I will update references but I honestly belive there is no much difference to the engine itself :) so seems like non critical.

If your project is .NET5 then you should be able to use all new fatures right away
```cs
namespace ConsoleApp43
{
    public record Person
    {
        public string LastName { get; }
        public string FirstName { get; }

        public Person(string first, string last) => (FirstName, LastName) = (first, last);
    }

    class Program
    {
        static void Main(string[] args)
        {
            IRazorEngine razorEngine = new RazorEngine();
            var template = razorEngine.Compile< RazorEngineTemplateBase<Person>>("Hello @Model.FirstName @Model.LastName");

            string result = template.Run(instance =>
            {
                instance.Model = new Person("Your", "Name");
            });

            Console.WriteLine(result);
            Console.ReadKey();
        }
    }
}
```

**Comment by adoconnection** [comment]
done in https://www.nuget.org/packages/RazorEngineCore/2021.3.1

**Comment by kobruleht** [comment]
It causes compiler warning 

`Warning CS1701: Assuming assembly reference 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' used by 'MyApp' matches identity 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' of 'Microsoft.AspNetCore.Mvc.ViewFeatures', you may need to supply runtime policy
`

Microsoft.AspNetCore.Mvc.ViewFeatures, Version=5.0.0.0  does not exists in .NET 5
