### ISSUE TITLE
Async template writing not supported

### ISSUE THREAD

**Issue by kobruleht** [adoconnection/RazorEngineCore#48]
@Html.PartialAsync in template causes error.

How to add something like

``` C#
        protected async Task<IHtmlstring> PartialAsync<T>(string viewName, T model)
        {
            // http://stackoverflow.com/questions/483091/render-a-view-as-a-string
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return new Htmlstring  (sw.GetStringBuilder().ToString());
            }
        }
```

to Template base class so @Html.PartialAsync or partial tag helper can used. Unfortunately, async template writing is not supported.

**Comment by adoconnection** [comment]
have look at these pages:

https://github.com/adoconnection/RazorEngineCore/wiki/@Html-implementation-example
https://github.com/adoconnection/RazorEngineCore/wiki/@Include-and-@Layout

**Comment by kobruleht** [comment]
RazorEngineCore does not support async template writing which is required for Html.PartialAsync.  How to add this ?

https://github.com/wdcossey/RazorEngineCore.Extensions/issues/9#issuecomment-822072544

**Comment by wdcossey** [comment]
Created a PR [here](https://github.com/adoconnection/RazorEngineCore/pull/53) to add some `async` overloads to `IRazorEngineTemplate`, this is so I can implement `PartialAsync` (and `Partial`) to my extensions package.

Adding something like the following:

```csharp
@Html.Partial("Hello <b>@Model.Name</b>", new { Name = "Partial Template"}))

@(await Html.PartialAsync("Hello <b>@Model.Name</b>", new { Name = "Partial Template"}))

@(await Html.PartialAsync(() => "Hello <b>@Model.Name</b>", new { Name = "Partial Template"}))
```

However to use `PartialAsync` I will need and asynchronous implementation of `Write` in `IRazorEngineTemplate` to make the operation truly async, hence the PR.

**Comment by kobruleht** [comment]
According to   https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial
first parameeter is view name:

`@await Html.PartialAsync("_PartialName")`

This view may exist in Views\Shared directory in project and is compiled into application during build. PartialAsync should find compiled view in application by name and return its content as string.

**Comment by adoconnection** [comment]
can we consider this issue resolved?

**Comment by kobruleht** [comment]
The issue is open in https://github.com/wdcossey/RazorEngineCore.Extensions/issues/9

**Comment by adoconnection** [comment]
closing for now
