### ISSUE TITLE
How can I use LINQ

### ISSUE THREAD

**Issue by yamaritta** [adoconnection/RazorEngineCore#5]
I have model with IEnumerable and  need sort collection in Razor.
 ```csharp
    public class TestModel: RazorEngineTemplateBase
    {
        public string Name { get; set; }
        public IEnumerable<int> Items { get; set; }
    }

 var content = @"
@using System.Collections;
@using System.Collections.Generic;
@using System.Linq;

Hello @Name
@{ var  ordered = System.Linq.Enumerable.OrderByDescending(Items, x=>x.Order);
     @foreach (var item in ordered)
            {
               <p>@item</p>                  
            }
}
";
            RazorEngineCompiledTemplate<TestModel> template = razorEngine.Compile<TestModel>(content);

            string result = template.Run(instance =>
            {
                instance.Name = "Alexander";
                instance.Items = new List<int>() {5,2,9,1,7};
            });
```
Unable to compile template: 4i13fl12.2ad(8,19): error CS1069: The type name 'Enumerable' could not be found in the namespace 'System.Linq'. This type has been forwarded to assembly 'System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

I also tried to call OrderBy on model
var  ordered = Items.OrderByDescending(x=>x);

Unable to compile template: 0xdlwlef.t31(9,22): error CS1061: 'IEnumerable<int>' does not contain a definition for 'OrderByDescending' and no accessible extension method 'OrderByDescending' accepting a first argument of type 'IEnumerable<int>' could be found (are you missing a using directive or an assembly reference?)

**Comment by adoconnection** [comment]
Sure, shame on me I have not tested Linq :)

`Install-Package RazorEngineCore -Version 2020.3.3`

I've made:
1. Linq referenced by default
2. Parameter to be able reference external assemblies if needed 

If you would like to make model look more like traditional razor model, consider following code

```cs
string content = @"

   @foreach (var item in Model.Items.OrderByDescending(x => x))
   {
      <p>Number @item</p>                  
   }

";

RazorEngine razorEngine = new RazorEngine();
RazorEngineCompiledTemplate<RazorEngineTemplateBase<TestModel>> template = razorEngine.Compile<RazorEngineTemplateBase<TestModel>>(content);

string result = template.Run(instance =>
{
    instance.Model = new TestModel()
    {
        Name = "Hello",
        Items = new[] {3, 1, 2}
    };
});

Console.WriteLine(result);
```

**Comment by yamaritta** [comment]
Thanks for the fix. Seems like a good decision
