### ISSUE TITLE
Please add StrongName support

### ISSUE THREAD

**Issue by garryxiao** [adoconnection/RazorEngineCore#59]
Warning	CS8002	Referenced assembly 'RazorEngineCore, Version=2021.3.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Not a big deal but annoying without it.  Thanks.

**Comment by adoconnection** [comment]
Hi, do you by any chance have a recepie to quickly add strong name? Last time I did asssembly signing was several year ago :)

**Comment by garryxiao** [comment]
Create a snk file by opening a Visual Studio command prompt as Administrator
sn -k <YOUR SNK FILE NAME>.snk

Then in VS, properties/signing, choose the file and save. That's all.

**Comment by adoconnection** [comment]
https://www.nuget.org/packages/RazorEngineCore/2021.7.1

**Comment by garryxiao** [comment]
Thanks.
