### ISSUE TITLE
Layout not working

### ISSUE THREAD

**Issue by joshtate** [adoconnection/RazorEngineCore#62]
Following [the example from the wiki regarding layouts](https://github.com/adoconnection/RazorEngineCore/wiki/@Include-and-@Layout), (which stemmed from [this issue](https://github.com/adoconnection/RazorEngineCore/issues/8)) it doesn't compile.  This line:

```
MyCompiledTemplate compiledTemplate = razorEngine.Compile(template, parts);
```

results in this compilation error:

```
Argument 2: cannot convert from System.Collections.Generic.IDictionary<string, string>' to 'System.Action<RazorEngineCore.IRazorEngineCompilationOptionsBuilder>'
```

I've tried looking into the `IRazorEngineCompilationOptionsBuilder` for a feature to specify layouts, but I don't see anything.  Has this feature been removed?

**Comment by joshtate** [comment]
Nevermind.  Reading into the wiki further explains that you have to implement this yourself.  Disregard.

**Comment by adoconnection** [comment]
did that code work for you?
