### ISSUE TITLE
Unable to migrate from RazorEngine: "error: (19, 18) The name 'inherits' does not exist in the current context"

### ISSUE THREAD

**Issue by julealgon** [adoconnection/RazorEngineCore#63]
I'm currently trying to migrate away from the old `RazorEngine` v3.10.0 to `RazorEngineCore` v2.2.6. I changed the package and my project compiles. After getting a message related to the `@model` directive, I found out it is not supported in the Core version, and that, if one wants to have intellisense, one has to add an `@inherits` tag.

https://github.com/adoconnection/RazorEngineCore/wiki/Switch-from-RazorEngine-cshtml-templates#template

However, when I add that in place of the old `@model`, I get an exception:

```
 RazorEngine.Templating.TemplateCompilationException : Errors while compiling a Template.
    Please try the following to solve the situation:
      * If the problem is about missing/invalid references or multiple defines either try to load 
        the missing references manually (in the compiling appdomain!) or
        Specify your references manually by providing your own IReferenceResolver implementation.
        See https://antaris.github.io/RazorEngine/ReferenceResolver.html for details.
        Currently all references have to be available as files!
      * If you get 'class' does not contain a definition for 'member': 
            try another modelType (for example 'null' to make the model dynamic).
            NOTE: You CANNOT use typeof(dynamic) to make the model dynamic!
        Or try to use static instead of anonymous/dynamic types.
    More details about the error:
     - error: (19, 18) The name 'inherits' does not exist in the current context
```

I tried both:
- `@inherits RazorEngineCore.RazorEngineTemplateBase<MyModel>`
(which actually gives me red squiggly lines in the editor)
as well as
- `@inherits RazorEngine.Templating.TemplateBase<MyModel>`

What am I missing?

**Comment by adoconnection** [comment]
could you please post console app example to reproduce this exception?

**Comment by julealgon** [comment]
> could you please post console app example to reproduce this exception?

This will probably take substantial time to create on my end... this is a legacy application with lots of layers and complex logic surrounding this template. 

I was hoping someone would have an idea by just looking at the exception since it is so specific 😞 

I'll try a few more tests on my own and if it still fails, I'll see about creating an isolated repro.

**Comment by adoconnection** [comment]
Simply make console app with example how you invoke razorEngineCore

**Comment by julealgon** [comment]
> Simply make console app with example how you invoke razorEngineCore. 

Neither our templating logic nor our actual templates are "simple". Creating such a repro will take significant effort, and is not something I had in mind while making this conversion from `RazorEngine`. The breaking change is actually extremely unfortunate.

Removing the `@inherits` directive passed all our tests. Not ideal to live without the autocomplete but will do for now.

If you don't think there is an issue here and don't want to investigate based on the error I provided, feel free to close the issue. I'd advise checking what is going on though as it seems to be a clear bug on the library (assuming `@inherits` is supposed to work).

**Comment by Untit1ed** [comment]
@adoconnection please review this example with the same issue: https://github.com/Untit1ed/razorenginebug/blob/main/Program.cs

**Comment by adoconnection** [comment]
Don’t get me wrong. This is what I’m trying to do. @inherits itself works so there is something more. That’s why it would be extremely helpful you could provide console app that reproduce this problem. 

related issue:
https://github.com/adoconnection/RazorEngineCore/issues/13

**Comment by julealgon** [comment]
@adoconnection turns out I got confused here and thought your library was `RazorEngine.NetCore` instead of `RazorEngineCore`. The issue I was seeing was with `RazorEngine.NetCore` and not with this library.

I'm actually surprised now that you didn't notice this yourself after I mentioned "v2.2.6", since this library seems to use a very different versioning style (current version is 2021.3.1).

I briefly attempted to replace the dependency to point to this library but the amount of breaking changes in our code is very significant.

In any case, the premise here is invalid so I'm closing the issue. Apologies for the confusion on my end.

**Comment by neilgaietto** [comment]
@julealgon Any chance you figured out your issue here? I know this issue relates to a different library, but I am running into the exact same issue. My '@inherits' or '@model' isnt working when I upgraded to RazorEngine.NetCore. I've been pretty unsuccessful finding a solution so far, and your the first person I've seen with the same issue.  Any help is appreciated. Thank You!

**Comment by julealgon** [comment]
> @julealgon Any chance you figured out your issue here? I know this issue relates to a different library, but I am running into the exact same issue. My '@inherits' or '@model' isnt working when I upgraded to RazorEngine.NetCore. I've been pretty unsuccessful finding a solution so far, and your the first person I've seen with the same issue. Any help is appreciated. Thank You!

@neilgaietto when I was discussing this topic here, we were trying to leverage `RazorEngine.NetCore` due to its higher apparent level of compatibility with the old native libraries. However, we never got it to work 100% and we've since actually made the jump and migrated to `RazorEngineCore` while making the necessary adjustments to our previous logic. The decision to go with `RazorEngineCore` was made while we were still in the initial steps of this process, so we never managed to get a full solution working with `RazorEngine.NetCore`.

For that reason, I probably won't be able to help you with your issue. I'd recommend opening an issue in the other repo and/or posting a question to StackOverflow and see if you get any traction there.

**Comment by deveshv19** [comment]
> @julealgon Any chance you figured out your issue here? I know this issue relates to a different library, but I am running into the exact same issue. My '@inherits' or '@model' isnt working when I upgraded to RazorEngine.NetCore. I've been pretty unsuccessful finding a solution so far, and your the first person I've seen with the same issue. Any help is appreciated. Thank You!

@neilgaietto Did you got any solution to this? I am facing same issues with @inherit

**Comment by neilgaietto** [comment]
@deveshv19 Our solution was to use RazorEngineCore instead of RazorEngine.NetCore. It was the better choice between the two.

**Comment by joshua5822** [comment]
For future reference for other developers who come across this. I looked into source code for RazorEngine.NetCore and it looks like the upgrade to .Net Core 3 caused a loss of "@inherits" or "@model" support. If you use the same base template type on all of your razor views you can work around it with setting the BaseTemplateType in the TemplateServiceConfiguration. You won't have any intellisense for your template or model, but it will still be able to compile.

Switching over to this project will be a future task, since I need ViewBag, Layout, and Raw/Encoded support. Too busy to get those parts working now.
