### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by 304NotModified** [adoconnection/RazorEngineCore#66]
I like the release numbers with years, it's clear when it's older.

But does that mean we don't do Semantic Versioning? (see https://semver.org/).

**Comment by adoconnection** [comment]
semver is boring and makes me feel unhappy :)

To be serious, my practice tells me:
1. Breaking changes are rare for small libraries like RazorEngineCore and their nature is simple: new argument, property or class renamed. No big deal.
2. When breaking change occurs, noone will make security patches for previous versions, so you pretty much dont have any choise anyway and will have to update your code.

In expense for "kowing breaking change moment" you get a sense that you are working with somewhat fresh and supported product.

**Comment by adoconnection** [comment]
I would like to close this issue if you dont mind

**Comment by 304NotModified** [comment]
That's ok. The short answer is ok. I think as maintainer server brings great benefits. For example, RazorEngineCore.extensions is broken and you will only notice that at runtime.
