### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by 304NotModified** [adoconnection/RazorEngineCore#68]
Hey! I noticed this repo isn't building on a CI in the cloud. Do you like any help on setting this up? (AppVeyor, it's free for OSS)

It's my way to say: thx :)

**Comment by adoconnection** [comment]
Hi, that would be massive. Maybe we can try Github actions first?

**Comment by 304NotModified** [comment]
Github actions is also a good idea, but it's a bit less supported for .NET Framework AFAIK.

Trying Github actions now. I guess I need the convert the ExampleAppNET472.csproj to SDK format

**Comment by adoconnection** [comment]
Cool, thanks! I'll have a look asap
