### ISSUE TITLE
Problems migrating working template to library throwing weird errors

### ISSUE THREAD

**Issue by sdunn-Dev** [adoconnection/RazorEngineCore#70]
I have a project that I am migrating from WebForms to Blazor Servers side in .NET 5. The original project used this library from https://antaris.github.io/RazorEngine/. This library wasnt working and I wanted to use a library that was more supported. This library seems like a good fit. I have a report cshtml file that is 99% the same as the original working report (except for different @using statement locations, but it is lighting up and the projects have the proper project references), and code that is doing exactly what it originally did and getting a DTO that is exactly the same as the original. When I run the code I get the following errors: 

Unable to compile template: s1wj2dld.c0p(5,7): error CS0246: The type or namespace name 'Bridgespan' could not be found (are you missing a using directive or an assembly reference?)
s1wj2dld.c0p(6,7): error CS0246: The type or namespace name 'Bridgespan' could not be found (are you missing a using directive or an assembly reference?)
s1wj2dld.c0p(7,7): error CS0246: The type or namespace name 'Bridgespan' could not be found (are you missing a using directive or an assembly reference?)
s1wj2dld.c0p(8,7): error CS0246: The type or namespace name 'Bridgespan' could not be found (are you missing a using directive or an assembly reference?)
s1wj2dld.c0p(10,7): error CS0103: The name 'model' does not exist in the current context
s1wj2dld.c0p(13,2): error CS0103: The name 'Layout' does not exist in the current context
s1wj2dld.c0p(19,16): error CS0103: The name 'Enum' does not exist in the current context
s1wj2dld.c0p(19,38): error CS0246: The type or namespace name 'AnswerResult' could not be found (are you missing a using directive or an assembly reference?)
s1wj2dld.c0p(19,58): error CS0246: The type or namespace name 'AnswerResult' could not be found (are you missing a using directive or an assembly reference?)
s1wj2dld.c0p(19,109): error CS0246: The type or namespace name 'AnswerInfoAttribute' could not be found (are you missing a using directive or an assembly reference?)
s1wj2dld.c0p(22,9): error CS0103: The name 'AnswerResult' does not exist in the current context
s1wj2dld.c0p(24,9): error CS0103: The name 'AnswerResult' does not exist in the current context
s1wj2dld.c0p(26,9): error CS0103: The name 'AnswerResult' does not exist in the current context
s1wj2dld.c0p(28,9): error CS0103: The name 'AnswerResult' does not exist in the current context
s1wj2dld.c0p(30,9): error CS0103: The name 'AnswerResult' does not exist in the current context
s1wj2dld.c0p(32,9): error CS0103: The name 'AnswerResult' does not exist in the current context

Not sure what is missing since the project has the proper references. Check out this video that shows me walking through this here: https://www.screencast.com/t/irmDwQTo

I have also enclosed the reporting file. Any help figuring out how to get this to work would be great!
[PartialIndividualResults.zip](https://github.com/adoconnection/RazorEngineCore/files/6921353/PartialIndividualResults.zip)

**Comment by sdunn-Dev** [comment]
After posting this I went back to both the Blazor project and the Infrastructure projects (where the calls to the library are being used) and adding **Microsoft.AspNetCore.Razor** does not help. I thought maybe I was missing a dependency that wasnt picked up. Same errors.

**Comment by adoconnection** [comment]
Hi, there is important thing about Razor. In its core, it is a tool to make source code out of cshtml. This tool is extended by its consumers, for example ASP.NET MVC add its well known keywords like ```@html``` or ```@layout``` etc.

Antaris RazorEngine tryes to mimic MVC as much as possible while RazorEngineCore is not. So some features like Layouts has to be done in a different way. You may find it a bit complicated of a first look but there is a purpose for such design :)
https://github.com/adoconnection/RazorEngineCore/wiki/@Include-and-@Layout

Apparently when using RazorEngineCore inside template, you need to explicitly reference asseblies from ```@using``` section

![image](https://user-images.githubusercontent.com/499855/128168559-96aa8d3c-f30f-4361-8d0f-2d47b33c9db9.png)

**Comment by adoconnection** [comment]
[BlazorApp6-Server.zip](https://github.com/adoconnection/RazorEngineCore/files/6930613/BlazorApp6-Server.zip)
