### ISSUE TITLE
Partial Pages support

### ISSUE THREAD

**Issue by afelsing** [adoconnection/RazorEngineCore#77]
Hello,

We are using RazorEngineCore for our report templating needs (thank you for your time and effort!). 

For our current scenario, I'd like to break out parts of a report into components. These components could then be shared by other reports. 

Do you have a recommendation on how to achieve this?

Thanks!

**Comment by adoconnection** [comment]
Hi, thanks for kind words.

Basically you need to make ```CustomRazorEngineTemplate : RazorEngineTemplateBase``` where you can define new keywords and their logic and you can name them the way it fits you most

```cs
public class MyTemplateBase : RazorEngineTemplateBase
{
    public Func<string, object, string> IncludeCallback { get; set; }

    public string Include(string key, object model = null)
    {
        return this.IncludeCallback(key, model);
    }
}
```

and when you run this template you will have callback for rendering component where you can render your component
```cs
string result = template.Run(instance =>
{
    instance.Model = model;
    instance.IncludeCallback = (key, includeModel) => {
                // render your component, say, other razor engine template
    }
});
```

```html
<div>
     @Include("Logo", Model)
</div>
```

see wiki:
https://github.com/adoconnection/RazorEngineCore/wiki/@Include-and-@Layout
