### ISSUE TITLE
Error when trying to use @inherits directive

### ISSUE THREAD

**Issue by jfbueno** [adoconnection/RazorEngineCore#78]
I'm trying to use the `@inherits` directive (as the documentation says [here](https://github.com/adoconnection/RazorEngineCore/wiki/@model-and-Visual-Studio-IntelliSense)) in my template so I can use intellisense and code suggestions.

But the build is throwing this error:

> C:\project\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\template_detalhado_cshtml.g.cs(39,135): error CS0103: **The name 'StartTagHelperWritingScope' does not exist in the current context**

> C:\project\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\template_detalhado_cshtml.g.cs(39,163): error CS0103: **The name 'EndTagHelperWritingScope' does not exist in the current context**

> C:\project\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\template_detalhado_cshtml.g.cs(138,73): error CS0103: **The name 'CreateTagHelper' does not exist in the current context** 

Does anyone know why is this happening and how can I prevent it?

**Comment by adoconnection** [comment]
Can you post some code to reproduce this problem please

**Comment by jfbueno** [comment]
Yes. [This repo](https://github.com/jfbueno/RazorEngineTests) contains a project with a reproducible example.

This looks like some problem with the process of compiling the CSHTML itself and not something with RazorEngineCore.

**Comment by adoconnection** [comment]
Thanks for example!
This one is because dotnet tries to precompile view wich is wrong since its no longer part of MVC but standalone RazorEngineCore template.
Switching build action to **None** will fix this.

![image](https://user-images.githubusercontent.com/499855/144145550-ea98646a-c95a-4473-bf82-f6cd8d8b5af3.png)

**Comment by AaaBin** [comment]
Hi, I'm using RazorEngineCore with vscode. And I facing the same problem here. I tried add this in `.csproj`:
```
<ItemGroup>
    <None Include="MailTemplates/Template.cshtml" />
</ItemGroup>
```
But it has no effect. What should I do?
