### ISSUE TITLE
@Include templates

### ISSUE THREAD

**Issue by standamikes** [adoconnection/RazorEngineCore#8]
Is there any way of adding other templates or adding layout like it works in https://github.com/biohazard999/RazorEngine ?

For example :

`@{Layout = "_Layout";} `
or 
`@Include("footer")`

and after 

`razor.AddTemplate("_Layout", ".....");`

Thanks for your work

**Comment by nicklas669** [comment]
+1 for this, it would be nice.. I'm looking experimenting a little with this library and it seems I need to have all my markup in one template? It would be nice if you could separate templates into smaller pieces and then put them together..

**Comment by adoconnection** [comment]
Hi, I honestly think it is unnesesary complexity.
Since RazorEngine.Compile accept template as a string, one will need also to accept a `Dictionary (key, template)` to be able to resolve `@Include`. Well of course it is possible to implement, but should I?

I created wiki page with example, may I ask you to evaluate it:
https://github.com/adoconnection/RazorEngineCore/wiki/@Include-section

whats your opinion?

**Comment by Merlin04** [comment]
That looks like it can provide support for `@include`, but is it possible to have support for layouts?

**Comment by joplaal** [comment]
@Merlin04 Did you finally achieve some way to get it working with Layouts and sections? We use RazorEngine and we are trying to find a replacement, but we use extensivelly Layouts and sections.

**Comment by Merlin04** [comment]
@joplaal I did. For `@include` support follow the wiki page linked previously. To add a layout, edit the `MyTemplateBase` class to add the following code:

```csharp
public Action<string> LayoutCallback;

public string Layout
{
    get { return _layout; }
    set
    {
        _layout = value;
        LayoutCallback(_layout);
    }
}
```
Then, create a new class called `LayoutTemplateBase` with the following contents:
```csharp
public class LayoutTemplateBase : RazorEngineTemplateBase
{
    public string RenderBody => Model.RenderBody;
}
```
Now you have to modify `MyRazorEngine`. Add this code at the beginning of the Render method (the one labeled "fast", I didn't use the slow one):
```csharp
string templateLayout = string.Empty;
```
Add this code below `instance.IncludeCallback` in the Render method:
```csharp
instance.LayoutCallback = key =>
{
    templateLayout = key;
};
```
Then, change `return compiledTemplate.Run` to `string templateOutput = compiledTemplate.Run`.

By default the method returns a string, but you'll need to modify this by creating a class that has two properties, the contents and the layout name. Then, make the function return an instance of the class, with the contents being `templateOutput` and the layout being `templateLayout`.

Now, add a new method to `MyRazorEngine`:
```csharp
public string RenderLayout(RazorEngineCompiledTemplate<LayoutTemplateBase> compiledLayout, object model)
{
    return compiledLayout.Run(instance =>
    {
        if (!(model is AnonymousTypeWrapper))
        {
            model = new AnonymousTypeWrapper(model);
        }

        instance.Model = model;
    });
}
```
Finally, add this method to `MyRazorEngine`:
```csharp
public Dictionary<string, RazorEngineCompiledTemplate<IncludeTemplateBase>> GetCompiledIncludes(
    IDictionary<string, string> includes)
{
    RazorEngine razorEngine = new RazorEngine();
    return includes.ToDictionary(
        k => k.Key,
        v => razorEngine.Compile<IncludeTemplateBase>(v.Value, GetOptionsBuilder));
}
```
Now you can use this to compile a page with a layout:
```csharp
MyRazorEngine engine = new MyRazorEngine();
RazorEngine razorEngine = new RazorEngine();
// includes is a dictionary of your includes with their title as the key and the contents as the value
Dictionary<string, RazorEngineCompiledTemplate<IncludeTemplateBase>> compiledIncludes =
    engine.GetCompiledIncludes(includes);
RazorEngineCompiledTemplate<MyTemplateBase> compiledTemplate =
    razorEngine.Compile<MyTemplateBase>("Insert your page template here");
// In my application the output of Render is of type RenderedTemplate, you will probably need to change this
// If you want to pass a model to your template replace "new { }" with your model
RenderedTemplate renderedTemplate = engine.Render(compiledTemplate, compiledIncludes, new { });
RazorEngineCompiledTemplate<LayoutTemplateBase> compiledLayout =
    razorEngine.Compile<LayoutTemplateBase>("layout contents go here");
// May need to change renderedTemplate.Contents to what the property is called in your class
string output = engine.RenderLayout(compiledLayout, new { RenderBody = renderedTemplate.Contents });
```
Let me know if you run into any problems with this.

**Comment by adoconnection** [comment]
@Merlin04 epic!

**Comment by Merlin04** [comment]
I just realized that Razor syntax uses `@RenderBody()` instead of `@RenderBody`, I've adjusted the code to reflect this.

**Comment by adoconnection** [comment]
I have made Extension method for RazorEngineCore
https://github.com/adoconnection/RazorEngineCore/wiki/@Include-and-@Layout

```cs
string template = @"
    @{
        Layout = ""MyLayout"";
     }

    <h1>@Model.Title</h1>

    @Include(""outer"", Model)
";

IDictionary<string, string> parts = new Dictionary<string, string>()
{
        {"MyLayout", @"
            LAYOUT HEADER
                @RenderBody()
            LAYOUT FOOTER
        "},
        {"outer", "This is Outer include, <@Model.Title>, @Include(\"inner\")"},
        {"inner", "This is Inner include"}
};

RazorEngine razorEngine = new RazorEngine();

MyCompiledTemplate compiledTemplate = razorEngine.Compile(template, parts);

string result = compiledTemplate.Run(new { Title = "Hello" });
```

Output
```
LAYOUT HEADER

<h1>Hello</h1>
This is Outer include, <Hello>, This is Inner include

LAYOUT FOOTER
```
