### ISSUE TITLE
Is this right?

### ISSUE THREAD

**Issue by athinboy** [adoconnection/RazorEngineCore#80]
``
 IRazorEngine razorEngine = new RazorEngine();
            IRazorEngineCompiledTemplate<RazorEngineTemplateBase<DDLTable>> template 
                = razorEngine.Compile<RazorEngineTemplateBase<DDLTable>>(templateContent, builder =>
                {                   
                    builder.AddAssemblyReferenceByName("System.Collections");
                });
``

```
@for (var i = 0; i < @Model.Columns.Count; i++){
  var col2=@Model.Columns[i];
  Name: @col2.Name 
}
```
RazorEngineCore.RazorEngineCompilationException : Unable to compile template: mnoilfrp.af3(21,19): error CS1002: ; expected

But:
```
@for (var i = 0; i < @Model.Columns.Count; i++){
  var col2=@Model.Columns[i];
  <p>Name: @col2.Name</p> 
}
```

<p>Name: owner_code</p>
<p>Name: company_name_cn</p>
<p>Name: booking_no</p>
<p>Name: license</p>

**Comment by adoconnection** [comment]
Yes

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-5.0#explicit-line-transition

**Comment by athinboy** [comment]
thanks !
@adoconnection
