### ISSUE TITLE
Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Workspaces 3.3.1 requires Microsoft.CodeAnalysis.CSharp (= 3.3.1) but version Microsoft.CodeAnalysis.CSharp 3.4.0 was resolved

### ISSUE THREAD

**Issue by troncomputers** [adoconnection/RazorEngineCore#9]
Is there a chance to update dependency to the latest version?

**Comment by adoconnection** [comment]
At this point Microsoft.CodeAnalysis.CSharp is 3.4.0 version, looks like 3.3.1 dependency is on your side, could you please double check?

But meanwhile Microsoft released two updates:
Microsoft.CodeAnalysis.CSharp - 3.5.0
Microsoft.AspNetCore.Razor.Language - 3.1.2

Willl use those versions in next release

**Comment by troncomputers** [comment]
Would you be able to guide me how to update those? I have latest SDK, NuGet is not showing any updates...

**Comment by adoconnection** [comment]
👍 👍

**Comment by josephwambura** [comment]
> Would you be able to guide me how to update those? I have latest SDK, NuGet is not showing any updates...
> 
> **EDIT** It works now. I had to remove `Microsoft.VisualStudio.Web.CodeGeneration.Design`

What if one needs that?

**Comment by troncomputers** [comment]
@josephwambura 
Well, I am not using .NET Core 3.1 anymore. I jumped to .NET 6 + RazorEngineCore ver. 2022.8.1 and there is no problem with `Microsoft.VisualStudio.Web.CodeGeneration.Design`
