### ISSUE TITLE
Template Delegates are not supported

### ISSUE THREAD

**Issue by SaphireLattice** [adoconnection/RazorEngineCore#96]
It seems that they are added via the builder in RazorProjectEngine, with TemplateTargetExtension. But [builder method](https://github.com/adoconnection/RazorEngineCore/blob/c285822d6f1c96006c61053b5486e6c43e195b4f/RazorEngineCore/RazorEngine.cs#L60-L63) is completely inaccessible and impossible to extend with current API? That's kinda surprising it is not accessible and not able to be extended...

**Comment by adoconnection** [comment]
we can fix that :)

**Comment by SaphireLattice** [comment]
I'm guessing passing it as part of the options would work?

Oh also, the builder allows setting the default base class from which the template inherits, meaning that there's no need to append "@inherits" for default stuff as a text to the template?

**Comment by thomas-parrish** [comment]
> we can fix that :)

Are there still plans to implement this?

**Comment by adoconnection** [comment]
done in 2024.4.4
https://www.nuget.org/packages/RazorEngineCore/2024.4.1

```cs
IRazorEngineCompiledTemplate template1 = razorEngine.Compile("Hello <h1>@Model.Name</h1>", builder =>
{
    builder.Options.ProjectEngineBuilder = engineBuilder =>
    {
        engineBuilder.Features.Add(myCoolFeature);
    };
});
```
