### ISSUE TITLE
Property not parsed, when preceded with an escape character

### ISSUE THREAD

**Issue by JohnBerg60** [adoconnection/RazorEngineCore#97]
I use the most simple raw example:

```
IRazorEngineCompiledTemplate template = razorEngine.Compile(raw, builder =>
{
        builder.AddUsing("System");
});

return template.Run(templateVars);
```

Providing a raw string like this works just fine (notice the space before @ :
```
"Peripheralheader": "/*\n *\t @Model.Name \n *\tAutogenerated on @DateTime.Now\n */"
```

When I remove the spaces and run the template with this raw string:
```
"Peripheralheader": "/*\n *\t@Model.Name \n *\tAutogenerated on@DateTime.Now\n */"
```
the ouput is uncompiled, and the two vars a not recognized as vars.

**Comment by adoconnection** [comment]
Well, this is how Razor works. here this you suppoed to write 
Autogenerated @("on" + DateTime.Now)\n

**Comment by JohnBerg60** [comment]
And with this:
```
"Peripheralheader": "/*\n *\t@Model.Name
```
I do @("\t" + @Model.Name) ??

**Comment by adoconnection** [comment]
yep, thats what documentation suggest

![image](https://user-images.githubusercontent.com/499855/155216428-7a228edd-2c4f-4046-96d8-3e8eeb3cd0d6.png)
